version: '2'
services:
#  web:
#    depends_on:
#      - db
#    image: ingensi/play-framework
#    ports:
#      - 9000:9000
#    volumes:
#      - .:/app
#    volumes_from:
#      - sbt
#    stdin_open: true
#    command: activator run
  db:
    image: postgres:9.6
    volumes:
      - ./mounts/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
# sbt:
#    image: centos
#    volumes:
#     - ~/.ivy2:/root/.ivy2:rw
#     - ~/.ivy2:/home/docker/.ivy2:rw
#     - ~/.sbt:/root/.sbt:rw
#     - ~/.sbt:/home/docker/.sbt:rw
